# Generated by Django 4.2.7 on 2024-01-22 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_normal', models.DecimalField(decimal_places=4, max_digits=10)),
                ('tasa_real', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fecha', models.DateField()),
                ('moneda_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_base', to='polls.moneda')),
                ('moneda_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_objetivo', to='polls.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_enviada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mensajero', models.CharField(max_length=100)),
                ('costo_domicilio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20)),
                ('moneda_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_domicilio', to='polls.moneda')),
                ('moneda_enviada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_enviada', to='polls.moneda')),
                ('moneda_recibida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moneda_recibida', to='polls.moneda')),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_recibidas', to='polls.persona')),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_enviadas', to='polls.persona')),
                ('tasa_cambio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.tasacambio')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pais')),
            ],
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.provincia'),
        ),
        migrations.CreateModel(
            name='Fondo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.moneda')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.municipio')),
            ],
        ),
    ]
